using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using TriggeredAnimation;

namespace MonogameAutoGeneratedContent{
    public static class ContentManagerExtensions_pupila
    {        
        public static Animation LoadAnimation_pupila(this ContentManager content)
        {
            var texture = content.Load<Texture2D>("pupila");
            var animation = new FrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(0, 0, 476, 253),
                new Rectangle(0, 253, 476, 253)
            });

            return new Animation(texture, animation);
        }
    }
}