using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using TriggeredAnimation;

namespace MonogameAutoGeneratedContent{
    public static class ContentManagerExtensions_PalpebrasBemAbertas
    {        
        public static Animation LoadAnimation_PalpebrasBemAbertas(this ContentManager content)
        {
            var texture = content.Load<Texture2D>("PalpebrasBemAbertas");
            var animation = new FrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(0, 0, 476, 253),
                new Rectangle(476, 0, 476, 253),
                new Rectangle(0, 253, 476, 253),
                new Rectangle(476, 253, 476, 253),
                new Rectangle(0, 506, 476, 253),
                new Rectangle(476, 506, 476, 253),
                new Rectangle(0, 759, 476, 253)
            });

            return new Animation(texture, animation);
        }
    }
}