using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using TriggeredAnimation;

namespace MonogameAutoGeneratedContent{
    public static class ContentManagerExtensions_Boca
    {        
        public static Animation LoadAnimation_Boca(this ContentManager content)
        {
            var texture = content.Load<Texture2D>("Boca");
            var animation = new FrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(0+1, 0+1, 476-1, 253-1),
                new Rectangle(476+1, 0+1, 476-1, 253-1),
                new Rectangle(0+1, 253+1, 476-1, 253-1),
                new Rectangle(476+1, 253+1, 476-1, 253-1),
                new Rectangle(0+1, 506+1, 476-1, 253-1),
                new Rectangle(476+1, 506+1, 476-1, 253-1)
            });

            return new Animation(texture, animation);
        }
    }
}