using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using TriggeredAnimation;

namespace MonogameAutoGeneratedContent{
    public static class SpriteSheet_Carolina
    {
        private static Texture2D Texture;
        
        public static SimpleAnimation Load_Boca(ContentManager content)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new FrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(0, 0, 43, 24),
                new Rectangle(43, 0, 43, 24),
                new Rectangle(86, 0, 43, 24),
                new Rectangle(129, 0, 43, 24),
                new Rectangle(172, 0, 43, 24),
                new Rectangle(215, 0, 43, 24)
            });

            return new SimpleAnimation(Texture, animation);
        }

        public static SimpleAnimation Load_Corpo(ContentManager content)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new FrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(258, 0, 102, 127),
                new Rectangle(360, 0, 102, 127),
                new Rectangle(0, 127, 102, 127),
                new Rectangle(102, 127, 102, 127),
                new Rectangle(204, 127, 102, 127),
                new Rectangle(306, 127, 102, 127),
                new Rectangle(408, 127, 102, 127),
                new Rectangle(0, 254, 102, 127)
            });

            return new SimpleAnimation(Texture, animation);
        }

        public static SimpleAnimation Load_Palpebras_bem_abertas(ContentManager content)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new FrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(102, 254, 64, 23),
                new Rectangle(166, 254, 64, 23),
                new Rectangle(230, 254, 64, 23),
                new Rectangle(294, 254, 64, 23),
                new Rectangle(358, 254, 64, 23),
                new Rectangle(422, 254, 64, 23),
                new Rectangle(0, 381, 64, 23)
            });

            return new SimpleAnimation(Texture, animation);
        }

        public static SimpleAnimation Load_Palpebras_fechando(ContentManager content)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new FrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(64, 381, 67, 29),
                new Rectangle(131, 381, 67, 29),
                new Rectangle(198, 381, 67, 29),
                new Rectangle(265, 381, 67, 29),
                new Rectangle(332, 381, 67, 29),
                new Rectangle(399, 381, 67, 29),
                new Rectangle(0, 410, 67, 29),
                new Rectangle(67, 410, 67, 29),
                new Rectangle(134, 410, 67, 29),
                new Rectangle(201, 410, 67, 29),
                new Rectangle(268, 410, 67, 29)
            });

            return new SimpleAnimation(Texture, animation);
        }

        public static SimpleAnimation Load_Pupila(ContentManager content)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new FrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(335, 410, 45, 12),
                new Rectangle(380, 410, 45, 12)
            });

            return new SimpleAnimation(Texture, animation);
        }

    }
}