using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using TriggeredAnimation;

namespace MonogameAutoGeneratedContent{
    public static class File_eyes
    {        
        public static TextureAnimation CreateAnimation(ContentManager content)
        {
            var texture = content.Load<Texture2D>("eyes");
            var animation = new BaseAnimation(60, new Rectangle[]
            {
                
                new Rectangle(0, 0, 45, 11),
                new Rectangle(0, 11, 45, 11)
            });

            return new TextureAnimation(animation, texture);
        }
    }
}