using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using TriggeredAnimation;

namespace MonogameAutoGeneratedContent{
    public static class File_idle
    {        
        public static TextureAnimation CreateAnimation(ContentManager content)
        {
            var texture = content.Load<Texture2D>("idle");
            var animation = new BaseAnimation(60, new Rectangle[]
            {
                
                new Rectangle(0, 0, 101, 167),
                new Rectangle(101, 0, 101, 167),
                new Rectangle(202, 0, 101, 167),
                new Rectangle(303, 0, 101, 167),
                new Rectangle(404, 0, 101, 167),
                new Rectangle(0, 167, 101, 167),
                new Rectangle(101, 167, 101, 167),
                new Rectangle(202, 167, 101, 167)
            });

            return new TextureAnimation(animation, texture);
        }
    }
}