using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using TriggeredAnimation;

namespace MonogameAutoGeneratedContent{
    public static class File_eyes_muito_abertos
    {        
        public static TextureAnimation CreateAnimation(ContentManager content)
        {
            var texture = content.Load<Texture2D>("eyes_muito_abertos");
            var animation = new BaseAnimation(60, new Rectangle[]
            {
                
                new Rectangle(0, 0, 65, 20),
                new Rectangle(0, 20, 65, 20),
                new Rectangle(0, 40, 65, 20),
                new Rectangle(0, 60, 65, 20),
                new Rectangle(0, 80, 65, 20),
                new Rectangle(0, 100, 65, 20)
            });

            return new TextureAnimation(animation, texture);
        }
    }
}