using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using TriggeredAnimation;

namespace MonogameAutoGeneratedContent{
    public static class LoadAnimation_eyes
    {        
        public static Animation CreateAnimation_eyes(this ContentManager content)
        {
            var texture = content.Load<Texture2D>("eyes");
            var animation = new FrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(0, 0, 45, 11),
                new Rectangle(0, 11, 45, 11)
            });

            return new Animation(texture,animation);
        }
    }
}