using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using TriggeredAnimation;

namespace MonogameAutoGeneratedContent{
    public static class File_eyes2
    {        
        public static Animation CreateAnimation_eyes2(this ContentManager content)
        {
            var texture = content.Load<Texture2D>("eyes2");
            var animation = new FrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(0, 0, 67, 27),
                new Rectangle(67, 0, 67, 27),
                new Rectangle(134, 0, 67, 27),
                new Rectangle(0, 27, 67, 27),
                new Rectangle(67, 27, 67, 27),
                new Rectangle(134, 27, 67, 27),
                new Rectangle(0, 54, 67, 27),
                new Rectangle(67, 54, 67, 27),
                new Rectangle(134, 54, 67, 27),
                new Rectangle(0, 81, 67, 27),
                new Rectangle(67, 81, 67, 27),
                new Rectangle(67, 81, 67, 27),
                new Rectangle(67, 81, 67, 27),
                new Rectangle(67, 81, 67, 27)
            });

            return new Animation(texture, animation);
        }
    }
}