using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using TriggeredAnimation;

namespace MonogameAutoGeneratedContent{
    public static class SpriteSheet_Carolina
    {
        private static Texture2D Texture;
        
        public static SimpleAnimation Load_Boca(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(0, 0, 57, 37),
                new Rectangle(0, 0, 57, 37),
                new Rectangle(0, 0, 57, 37),
                new Rectangle(0, 0, 57, 37),
                new Rectangle(57, 0, 57, 37),
                new Rectangle(57, 0, 57, 37),
                new Rectangle(57, 0, 57, 37),
                new Rectangle(57, 0, 57, 37),
                new Rectangle(57, 0, 57, 37),
                new Rectangle(57, 0, 57, 37),
                new Rectangle(57, 0, 57, 37),
                new Rectangle(57, 0, 57, 37),
                new Rectangle(57, 0, 57, 37),
                new Rectangle(57, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(114, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(171, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(228, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37),
                new Rectangle(285, 0, 57, 37)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

        public static SimpleAnimation Load_Boca_entristecendo(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(342, 0, 40, 11),
                new Rectangle(382, 0, 40, 11),
                new Rectangle(422, 0, 40, 11),
                new Rectangle(462, 0, 40, 11),
                new Rectangle(0, 37, 40, 11)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

        public static SimpleAnimation Load_Boca_triste(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(40, 37, 32, 13),
                new Rectangle(72, 37, 32, 13),
                new Rectangle(104, 37, 32, 13),
                new Rectangle(136, 37, 32, 13),
                new Rectangle(168, 37, 32, 13),
                new Rectangle(200, 37, 32, 13)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

        public static SimpleAnimation Load_Controle(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(232, 37, 65, 41)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

        public static SimpleAnimation Load_Corpo(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(297, 37, 102, 127),
                new Rectangle(399, 37, 102, 127),
                new Rectangle(0, 164, 102, 127),
                new Rectangle(102, 164, 102, 127),
                new Rectangle(204, 164, 102, 127),
                new Rectangle(306, 164, 102, 127),
                new Rectangle(408, 164, 102, 127),
                new Rectangle(0, 291, 102, 127)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

        public static SimpleAnimation Load_Mao_direita(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(102, 291, 32, 34),
                new Rectangle(134, 291, 32, 34),
                new Rectangle(166, 291, 32, 34),
                new Rectangle(198, 291, 32, 34)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

        public static SimpleAnimation Load_Mao_esquerda(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(230, 291, 32, 34),
                new Rectangle(262, 291, 32, 34),
                new Rectangle(294, 291, 32, 34),
                new Rectangle(326, 291, 32, 34)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

        public static SimpleAnimation Load_Palpebras_abertas(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(358, 291, 64, 18)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

        public static SimpleAnimation Load_Palpebras_arregaladas(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(422, 291, 64, 23),
                new Rectangle(0, 418, 64, 23)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

        public static SimpleAnimation Load_Palpebras_arregalando(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(64, 418, 67, 31),
                new Rectangle(131, 418, 67, 31),
                new Rectangle(198, 418, 67, 31),
                new Rectangle(265, 418, 67, 31),
                new Rectangle(332, 418, 67, 31),
                new Rectangle(399, 418, 67, 31),
                new Rectangle(0, 449, 67, 31),
                new Rectangle(67, 449, 67, 31)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

        public static SimpleAnimation Load_Palpebras_fechando(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(134, 449, 64, 31),
                new Rectangle(198, 449, 64, 31),
                new Rectangle(262, 449, 64, 31),
                new Rectangle(326, 449, 64, 31),
                new Rectangle(390, 449, 64, 31),
                new Rectangle(0, 480, 64, 31),
                new Rectangle(64, 480, 64, 31),
                new Rectangle(128, 480, 64, 31)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

        public static SimpleAnimation Load_Pupila(ContentManager content, int X = 0, int Y = 0)
        {
            if (Texture == null)
               Texture = content.Load<Texture2D>("Carolina");
            var animation = new SequentialFrameChooser(60, new Rectangle[]
            {
                
                new Rectangle(192, 480, 42, 7),
                new Rectangle(234, 480, 42, 7)
            });

            return new SimpleAnimation(Texture, animation, X, Y);
        }

    }
}