using Microsoft.Xna.Framework.Content;
using MonogameAutoGeneratedContent;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TriggeredAnimation;

namespace WindowsAnimation
{
    public static class RoundButtonAnimator
    {
        //static SimpleAnimation botao;
        //static SimpleAnimation botao_apertando;
        //static SimpleAnimation botao_desapertando;
        //static SimpleAnimation botao_apertado;

        public static Animator Create(ContentManager Content, int X, int Y, string flag)
        {           
            //if (botao == null)
            //{
                var botao = SpriteSheet_Carolina.Load_Botao_redondo(Content, 15, 15);
                var botao_apertando = SpriteSheet_Carolina.Load_Botao_redondo_apertando(Content);
                 botao_apertando.SetFrameRate(20);
                var botao_desapertando = SpriteSheet_Carolina.Load_Botao_redondo_apertando(Content).Reverse();
                 botao_desapertando.SetFrameRate(20);
                var botao_apertado = SpriteSheet_Carolina.Load_Botao_redondo_apertado(Content, 19, 17);
            //}

            return new Animator(
                X ,
                Y ,
                new FlaggedAnimationTransitionRule(botao, botao_apertando, flag),
                new AnimationTransitionRule(botao_apertando, botao_apertado),
                new UnFlaggedAnimationTransitionRule(botao_apertado, botao_desapertando, flag),
                new AnimationTransitionRule(botao_desapertando, botao)
            );
        }
    }
}
